### ISSUE TITLE
Middleware Security

### ISSUE THREAD

**Issue by ai-n0808** [Team-Strawberry-CC36/backend#36]
We need to catch the user cookie, and append it into the request.

```
app.use("/security", (req, res, next) => {

// 1. Get cookie
const userId = req.getCookie() // 
if (reqId) {
	req.body.userId = userId;
next()
} else {
	// Go away!
}
})
```

**Comment by brianaqp** [comment]
I think this was completed by Daniel.

**Comment by DanielWilliamParsons** [comment]
I'm not sure what middleware security is. I didn't do this.

The user's cookie is authenticated by Firebase - this is what I did.

The process is as follows (as far as I understand):
**Step 1**: Login or Registration - receive a temporary token on frontend from firebase. (Completed by Andy)

**Step 2**: Frontend sends user info and token to our backend. (To do - I started an issue for the front end project - issue 31)

**Step 3**: On the backend, authenticate the token with firebase and receive a session cookie from firebase (I wrote this code in auth folder using Firebase)

**Step 4**: If registering, add any user data to our database, e.g., uid. If logging in, retrieve user data from our database (I created an issue for this as issue #49 because it still needs to be done. I would have done it, but I'm not too confident with prisma yet. I wrote an interface, but it might need updating.)

**Step 5**: Send cookie received from firebase back to the frontend, and any other data (e.g., user info from our database) (This has been completed as part of Firebase implementation)

**Step 6**: Any time user makes a request verifySessionCookie on backend through Firebase (I wrote this code in auth folder as part of Firebase), but the verifySessionCookie needs applying to the routes we need authenticating.
